import type { Metadata } from "next";
import "./globals.css";
import Providers from "./components/Providers";
import { Kumbh_Sans } from "next/font/google";
import { UserProvider } from "../context/userContext";

const kumbh_Sans = Kumbh_Sans({ weight: "300", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tworkout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kumbh_Sans.className}>
        <Providers>
          <UserProvider> {/* Wrap the children with UserProvider */}
            {children}
          </UserProvider>
          </Providers>
      </body>
    </html>
  );
}
