import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Kumbh_Sans } from 'next/font/google'

const kumbh_Sans = Kumbh_Sans({ weight:'300', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "tworkout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kumbh_Sans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
